version: '3.9'

services:
  api:
    build: .
    container_name: poem-generator-api
    ports:
      - "8080:3000"  # Expose 3000 inside container as 8080 on host
    environment:
      NODE_ENV: production
      PORT: 3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}  # Load from .env or VPS export
    volumes:
      - .:/app
      - /app/node_modules  # Avoid host-to-container node_modules conflict
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
