
services:
  poem-generator-api:
    build: .
    container_name: poem-generator-api
    ports:
    - "3002:3000"  # Expose port 3000 on the host
    networks:
    - nginx-network
    environment:
      NODE_ENV: production
      PORT: 3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}  # Load from .env or VPS export
    volumes:
      - .:/app
      - /app/node_modules  # Avoid host-to-container node_modules conflict
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
